name: CI Pipeline

on:
  push:
    branches: [ "main" ]   # Runs when code is pushed to main
  pull_request:
    branches: [ "main" ]   # Runs on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests (we’ll add later)
    - name: Run Tests
      run: echo "No tests yet!"

    # Run the app (for verification)
    - name: Run app
      run: npm start &
